Project\StoreBundle\Entity\Movie:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        actors:
            type: text
        cover:
            type: string
            length: 255
        price:
            type: decimal
            scale: 2
    manyToOne:
        genre:
            targetEntity: Genre
            inversedBy: movies
            joinColumn:
                name: genre_id
                referencedColumnName: id
    oneToMany:
        recenzje:
            targetEntity: Recenzja
            mappedBy: movie"

    lifecycleCallbacks: {  }
