project_store_homepage:
    path:     /
    defaults: { _controller: ProjectStoreBundle:Movie:index }

project_store_movies:
    path:     /
    defaults: { _controller: ProjectStoreBundle:Movie:index }
