project_store_homepage:
    path:     /
    defaults: { _controller: ProjectStoreBundle:Movie:index }

project_store_genre:
    path:     /genres/{name}
    defaults: { _controller: ProjectStoreBundle:Movie:genre }

project_store_movie:
    path:     /movie/{slug}
    defaults: { _controller: ProjectStoreBundle:Movie:movie }

project_store_recenzja_add:
    path:     /movie/{slug}/Review/add
    defaults: { _controller: ProjectStoreBundle:Review:add }

project_store_recenzowane:
    path:     /recenzowane
    defaults: { _controller: ProjectStoreBundle:Movie:recenzowane }

project_store_koszyk:
    path:     /koszyk
    defaults: { _controller: ProjectStoreBundle:Koszyk:koszyk }